// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateBookings(ctx context.Context, arg CreateBookingsParams) (Booking, error)
	CreateBusinessHours(ctx context.Context, arg CreateBusinessHoursParams) (BusinessHour, error)
	CreateBusinesses(ctx context.Context, arg CreateBusinessesParams) (Business, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBooking(ctx context.Context, id int64) (Booking, error)
	DeleteBusiness(ctx context.Context, id int64) (Business, error)
	DeleteBusinessHour(ctx context.Context, id int64) (BusinessHour, error)
	DeleteReview(ctx context.Context, id int64) (Review, error)
	DeleteUser(ctx context.Context, id int64) (User, error)
	GetBooking(ctx context.Context, id int64) (Booking, error)
	GetBusinessHour(ctx context.Context, id int64) (BusinessHour, error)
	GetBusinesses(ctx context.Context, id int64) (Business, error)
	GetReview(ctx context.Context, id int64) (Review, error)
	GetUser(ctx context.Context, id int64) (User, error)
	ListBookings(ctx context.Context, arg ListBookingsParams) ([]Booking, error)
	ListBusinessHours(ctx context.Context, arg ListBusinessHoursParams) ([]BusinessHour, error)
	ListBusinesses(ctx context.Context, arg ListBusinessesParams) ([]Business, error)
	ListReviews(ctx context.Context, arg ListReviewsParams) ([]Review, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateBooking(ctx context.Context, arg UpdateBookingParams) error
	UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) error
	UpdateBusinessHour(ctx context.Context, arg UpdateBusinessHourParams) error
	UpdateReview(ctx context.Context, arg UpdateReviewParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
