// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"encoding/json"
	"time"
)

type Booking struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	BusinessID int64     `json:"business_id"`
	Service    string    `json:"service"`
	Date       time.Time `json:"date"`
	Status     string    `json:"status"`
	CreatedAt  time.Time `json:"created_at"`
}

type Business struct {
	ID        int64           `json:"id"`
	Owner     int64           `json:"owner"`
	Name      string          `json:"name"`
	Address   string          `json:"address"`
	Lattitude float64         `json:"lattitude"`
	Longitude float64         `json:"longitude"`
	Phone     string          `json:"phone"`
	Email     string          `json:"email"`
	Category  string          `json:"category"`
	Services  json.RawMessage `json:"services"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type BusinessHour struct {
	ID         int64     `json:"id"`
	BusinessID int64     `json:"business_id"`
	DayOfWeek  string    `json:"day_of_week"`
	OpenTime   time.Time `json:"open_time"`
	CloseTime  time.Time `json:"close_time"`
}

type Review struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	BusinessID int64     `json:"business_id"`
	Rating     int32     `json:"rating"`
	Comment    string    `json:"comment"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Phone     string    `json:"phone"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
